# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f100da33d18c2d762f48a4c0e66f301c16cd6edeb21bd92b4794aa5de5e849b149fb130417c0916d324a3cc135d7d8eec28e5755ea7fc5b089a2ba0952d5a5ab

test:
  secret_key_base: a2e5570161c1e6895bd7cf15df86cbb68503fec2ab4a393dbce353299d3f552646768b30bc3bb5432fa27fb2793f35300142823744fb855bbee0a7eaa0ec612b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
